// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

type Vault struct {
	VaultID        string  `db:"vault_id" json:"vault_id"`
	VaultName      string  `db:"vault_name" json:"vault_name"`
	OwnerID        string  `db:"owner_id" json:"owner_id"`
	CreatedAt      string  `db:"created_at" json:"created_at"`
	UpdatedAt      string  `db:"updated_at" json:"updated_at"`
	ScheduleDelete *string `db:"schedule_delete" json:"schedule_delete"`
}
