// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: vaults.sql

package db

import (
	"context"
)

const getVault = `-- name: GetVault :one
SELECT vault_id, vault_name, owner_id, created_at, updated_at, schedule_delete FROM vaults WHERE vault_name = ?1 AND owner_id = ?2
`

type GetVaultParams struct {
	VaultName string `db:"vault_name" json:"vault_name"`
	OwnerID   string `db:"owner_id" json:"owner_id"`
}

func (q *Queries) GetVault(ctx context.Context, arg GetVaultParams) (Vault, error) {
	row := q.db.QueryRowContext(ctx, getVault, arg.VaultName, arg.OwnerID)
	var i Vault
	err := row.Scan(
		&i.VaultID,
		&i.VaultName,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ScheduleDelete,
	)
	return i, err
}
