// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package db

import (
	"context"
)

const userExistsWithEmail = `-- name: UserExistsWithEmail :one
SELECT email FROM users WHERE email = ?1
`

func (q *Queries) UserExistsWithEmail(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRowContext(ctx, userExistsWithEmail, email)
	err := row.Scan(&email)
	return email, err
}
