// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/juancwu/secrething/internal/server/permissions"
)

type Permission struct {
	PermissionID   string                     `db:"permission_id" json:"permission_id"`
	VaultID        string                     `db:"vault_id" json:"vault_id"`
	GranteeType    string                     `db:"grantee_type" json:"grantee_type"`
	GranteeID      string                     `db:"grantee_id" json:"grantee_id"`
	PermissionBits permissions.PermissionBits `db:"permission_bits" json:"permission_bits"`
	GrantedBy      string                     `db:"granted_by" json:"granted_by"`
	CreatedAt      string                     `db:"created_at" json:"created_at"`
	UpdatedAt      string                     `db:"updated_at" json:"updated_at"`
}

type Secret struct {
	SecretID        string `db:"secret_id" json:"secret_id"`
	VaultID         string `db:"vault_id" json:"vault_id"`
	Name            string `db:"name" json:"name"`
	Value           []byte `db:"value" json:"value"`
	CreatedByUserID UserID `db:"created_by_user_id" json:"created_by_user_id"`
	CreatedAt       string `db:"created_at" json:"created_at"`
	UpdatedAt       string `db:"updated_at" json:"updated_at"`
}

type Team struct {
	TeamID          string  `db:"team_id" json:"team_id"`
	Name            string  `db:"name" json:"name"`
	Description     *string `db:"description" json:"description"`
	CreatedByUserID UserID  `db:"created_by_user_id" json:"created_by_user_id"`
	CreatedAt       string  `db:"created_at" json:"created_at"`
	UpdatedAt       string  `db:"updated_at" json:"updated_at"`
}

type Token struct {
	TokenID    TokenID `db:"token_id" json:"token_id"`
	UserID     UserID  `db:"user_id" json:"user_id"`
	TokenType  string  `db:"token_type" json:"token_type"`
	ClientType string  `db:"client_type" json:"client_type"`
	ExpiresAt  string  `db:"expires_at" json:"expires_at"`
	CreatedAt  string  `db:"created_at" json:"created_at"`
}

type User struct {
	UserID              UserID  `db:"user_id" json:"user_id"`
	Email               string  `db:"email" json:"email"`
	PasswordHash        string  `db:"password_hash" json:"password_hash"`
	Name                *string `db:"name" json:"name"`
	EmailVerified       bool    `db:"email_verified" json:"email_verified"`
	TotpSecret          *string `db:"totp_secret" json:"totp_secret"`
	TotpEnabled         bool    `db:"totp_enabled" json:"totp_enabled"`
	FailedLoginAttempts *int64  `db:"failed_login_attempts" json:"failed_login_attempts"`
	LastFailedLoginAt   *string `db:"last_failed_login_at" json:"last_failed_login_at"`
	AccountLockedUntil  *string `db:"account_locked_until" json:"account_locked_until"`
	CreatedAt           string  `db:"created_at" json:"created_at"`
	UpdatedAt           string  `db:"updated_at" json:"updated_at"`
}

type UsersTeam struct {
	UserID    UserID `db:"user_id" json:"user_id"`
	TeamID    string `db:"team_id" json:"team_id"`
	CreatedAt string `db:"created_at" json:"created_at"`
	UpdatedAt string `db:"updated_at" json:"updated_at"`
}

type Vault struct {
	VaultID         string  `db:"vault_id" json:"vault_id"`
	Name            string  `db:"name" json:"name"`
	Description     *string `db:"description" json:"description"`
	CreatedByUserID UserID  `db:"created_by_user_id" json:"created_by_user_id"`
	OwnerType       string  `db:"owner_type" json:"owner_type"`
	OwnerID         string  `db:"owner_id" json:"owner_id"`
	CreatedAt       string  `db:"created_at" json:"created_at"`
	UpdatedAt       string  `db:"updated_at" json:"updated_at"`
}
