// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: magic_links.sql

package db

import (
	"context"
)

const createMagicLink = `-- name: CreateMagicLink :exec
INSERT INTO magic_links
(token, user_id, created_at, expires_at)
VALUES
(?, ?, ?, ?)
`

type CreateMagicLinkParams struct {
	Token     string
	UserID    string
	CreatedAt string
	ExpiresAt string
}

func (q *Queries) CreateMagicLink(ctx context.Context, arg CreateMagicLinkParams) error {
	_, err := q.db.ExecContext(ctx, createMagicLink,
		arg.Token,
		arg.UserID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const getMagicLink = `-- name: GetMagicLink :one
SELECT token, user_id, created_at, expires_at
FROM magic_links
WHERE token = ? AND user_id = ?
`

type GetMagicLinkParams struct {
	Token  string
	UserID string
}

func (q *Queries) GetMagicLink(ctx context.Context, arg GetMagicLinkParams) (MagicLink, error) {
	row := q.db.QueryRowContext(ctx, getMagicLink, arg.Token, arg.UserID)
	var i MagicLink
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const removeMagicLink = `-- name: RemoveMagicLink :exec
DELETE FROM magic_links
WHERE token = ? AND user_id = ?
`

type RemoveMagicLinkParams struct {
	Token  string
	UserID string
}

func (q *Queries) RemoveMagicLink(ctx context.Context, arg RemoveMagicLinkParams) error {
	_, err := q.db.ExecContext(ctx, removeMagicLink, arg.Token, arg.UserID)
	return err
}
