// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type AccessLog struct {
	ID           string      `db:"id"`
	UserID       *string     `db:"user_id"`
	BentoID      *string     `db:"bento_id"`
	GroupID      *string     `db:"group_id"`
	BentoTokenID *string     `db:"bento_token_id"`
	Action       string      `db:"action"`
	Details      interface{} `db:"details"`
	AccessedAt   string      `db:"accessed_at"`
}

type AuthToken struct {
	ID        string `db:"id"`
	UserID    string `db:"user_id"`
	CreatedAt string `db:"created_at"`
	ExpiresAt string `db:"expires_at"`
	TokenType string `db:"token_type"`
}

type Bento struct {
	ID        string `db:"id"`
	UserID    string `db:"user_id"`
	Name      string `db:"name"`
	CreatedAt string `db:"created_at"`
	UpdatedAt string `db:"updated_at"`
}

type BentoIngredient struct {
	ID        string `db:"id"`
	BentoID   string `db:"bento_id"`
	Name      string `db:"name"`
	Value     []byte `db:"value"`
	CreatedAt string `db:"created_at"`
	UpdatedAt string `db:"updated_at"`
}

type BentoPermission struct {
	UserID    string `db:"user_id"`
	BentoID   string `db:"bento_id"`
	Bytes     []byte `db:"bytes"`
	CreatedAt string `db:"created_at"`
	UpdatedAt string `db:"updated_at"`
}

type BentoToken struct {
	ID         string  `db:"id"`
	BentoID    string  `db:"bento_id"`
	TokenSalt  []byte  `db:"token_salt"`
	CreatedBy  string  `db:"created_by"`
	CreatedAt  string  `db:"created_at"`
	LastUsedAt *string `db:"last_used_at"`
	ExpiresAt  *string `db:"expires_at"`
}

type Group struct {
	ID        string `db:"id"`
	Name      string `db:"name"`
	OwnerID   string `db:"owner_id"`
	CreatedAt string `db:"created_at"`
	UpdatedAt string `db:"updated_at"`
}

type GroupInvitation struct {
	ID        string `db:"id"`
	UserID    string `db:"user_id"`
	GroupID   string `db:"group_id"`
	CreatedAt string `db:"created_at"`
	ExpiresAt string `db:"expires_at"`
}

type GroupPermission struct {
	GroupID   string `db:"group_id"`
	BentoID   string `db:"bento_id"`
	Level     int64  `db:"level"`
	CreatedAt string `db:"created_at"`
	UpdatedAt string `db:"updated_at"`
}

type TotpRecoveryCode struct {
	ID        string  `db:"id"`
	UserID    string  `db:"user_id"`
	Code      string  `db:"code"`
	Used      bool    `db:"used"`
	CreatedAt string  `db:"created_at"`
	UsedAt    *string `db:"used_at"`
}

type User struct {
	ID            string  `db:"id"`
	Email         string  `db:"email"`
	Password      string  `db:"password"`
	Nickname      string  `db:"nickname"`
	EmailVerified bool    `db:"email_verified"`
	TotpSecret    *string `db:"totp_secret"`
	TotpLocked    bool    `db:"totp_locked"`
	CreatedAt     string  `db:"created_at"`
	UpdatedAt     string  `db:"updated_at"`
}

type UsersGroup struct {
	UserID    string `db:"user_id"`
	GroupID   string `db:"group_id"`
	CreatedAt string `db:"created_at"`
}
