// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions
(token_salt, user_id, ip, last_activity)
VALUES
(?, ?, ?, ?)
RETURNING token_id
`

type CreateSessionParams struct {
	TokenSalt    []byte
	UserID       string
	Ip           sql.NullString
	LastActivity string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.TokenSalt,
		arg.UserID,
		arg.Ip,
		arg.LastActivity,
	)
	var token_id string
	err := row.Scan(&token_id)
	return token_id, err
}
