// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: totp_recovery_codes.sql

package db

import (
	"context"
)

const newRecoveryCodes = `-- name: NewRecoveryCodes :exec
INSERT INTO totp_recovery_codes
(user_id, created_at, code)
VALUES
(?1, ?2, ?3),
(?1, ?2, ?4),
(?1, ?2, ?5),
(?1, ?2, ?6),
(?1, ?2, ?7),
(?1, ?2, ?8)
`

type NewRecoveryCodesParams struct {
	UserID    string
	CreatedAt string
	Code      string
	Code_2    string
	Code_3    string
	Code_4    string
	Code_5    string
	Code_6    string
}

func (q *Queries) NewRecoveryCodes(ctx context.Context, arg NewRecoveryCodesParams) error {
	_, err := q.db.ExecContext(ctx, newRecoveryCodes,
		arg.UserID,
		arg.CreatedAt,
		arg.Code,
		arg.Code_2,
		arg.Code_3,
		arg.Code_4,
		arg.Code_5,
		arg.Code_6,
	)
	return err
}

const removeUserRecoveryCodes = `-- name: RemoveUserRecoveryCodes :exec
DELETE FROM totp_recovery_codes
WHERE user_id = ?
`

func (q *Queries) RemoveUserRecoveryCodes(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, removeUserRecoveryCodes, userID)
	return err
}
