// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: totp_recovery_codes.sql

package db

import (
	"context"
)

const getRecoveryCode = `-- name: GetRecoveryCode :one
SELECT id, user_id, code, used, created_at, used_at FROM totp_recovery_codes
WHERE user_id = ? AND code = ?
`

type GetRecoveryCodeParams struct {
	UserID string `db:"user_id" json:"user_id"`
	Code   string `db:"code" json:"code"`
}

func (q *Queries) GetRecoveryCode(ctx context.Context, arg GetRecoveryCodeParams) (TotpRecoveryCode, error) {
	row := q.db.QueryRowContext(ctx, getRecoveryCode, arg.UserID, arg.Code)
	var i TotpRecoveryCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.Used,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return i, err
}

const newRecoveryCodes = `-- name: NewRecoveryCodes :exec
INSERT INTO totp_recovery_codes
(user_id, created_at, code)
VALUES
(?1, ?2, ?3),
(?1, ?2, ?4),
(?1, ?2, ?5),
(?1, ?2, ?6),
(?1, ?2, ?7),
(?1, ?2, ?8)
`

type NewRecoveryCodesParams struct {
	UserID    string `db:"user_id" json:"user_id"`
	CreatedAt string `db:"created_at" json:"created_at"`
	Code      string `db:"code" json:"code"`
	Code_2    string `db:"code_2" json:"code_2"`
	Code_3    string `db:"code_3" json:"code_3"`
	Code_4    string `db:"code_4" json:"code_4"`
	Code_5    string `db:"code_5" json:"code_5"`
	Code_6    string `db:"code_6" json:"code_6"`
}

func (q *Queries) NewRecoveryCodes(ctx context.Context, arg NewRecoveryCodesParams) error {
	_, err := q.db.ExecContext(ctx, newRecoveryCodes,
		arg.UserID,
		arg.CreatedAt,
		arg.Code,
		arg.Code_2,
		arg.Code_3,
		arg.Code_4,
		arg.Code_5,
		arg.Code_6,
	)
	return err
}

const removeUserRecoveryCodes = `-- name: RemoveUserRecoveryCodes :exec
DELETE FROM totp_recovery_codes
WHERE user_id = ?
`

func (q *Queries) RemoveUserRecoveryCodes(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, removeUserRecoveryCodes, userID)
	return err
}

const useRecoveryCode = `-- name: UseRecoveryCode :exec
UPDATE totp_recovery_codes SET used = true WHERE user_id = ? AND code = ?
`

type UseRecoveryCodeParams struct {
	UserID string `db:"user_id" json:"user_id"`
	Code   string `db:"code" json:"code"`
}

func (q *Queries) UseRecoveryCode(ctx context.Context, arg UseRecoveryCodeParams) error {
	_, err := q.db.ExecContext(ctx, useRecoveryCode, arg.UserID, arg.Code)
	return err
}
