name: "[Web] Code Quality"

on:
  push:
    branches: ["main"]
    paths:
      - "web/**"
  pull_request:
    branches: ["main"]
    paths:
      - "web/**"

jobs:
  quality:
    runs-on: ubuntu-latest
    working-directory: ./web
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci .
